### ISSUE TITLE
Discrepancy between telemetry and roll prediction

### ISSUE THREAD

**Issue by taldcroft** [sot/ska_sun#2]
In quick testing I noticed an offset of up to 0.4 deg between the off-nominal roll value here and the `roll` value in telemetry.  The latter uses the full Sun and Chandra ephemeris, but I don't think that is enough to generate this offset (would expect up to 0.1 deg from that at worst case).  The Sun position prediction is supposed to be good to a few arcsec.  Right now half-degree accuracy is OK, but it might be worth chasing this down.

**Comment by jeanconn** [comment]
I haven't done the work here to just look at differences, but is this widespread or do you have a good example time range for the issue?

**Comment by taldcroft** [comment]
I think it is systematic but also have not done any real characterization. Jan's observation shows the issue.

**Comment by jeanconn** [comment]
Note to self then:  start with obsid 17198
​
