### ISSUE TITLE
Allow specifying get_sun_pitch_yaw coordinate convention and change default

### ISSUE THREAD

**Issue by taldcroft** [sot/ska_sun#30]
The current definition of yaw about the sun line matches ORviewer, but this does not match the engineering convention where +yaw is in the same sense as spacecraft body yaw.

The new default should match the engineering sense, go from 0 to 360, and have zero be defined as the ECI z-axis if the Sun is at exactly RA = Dec = 0.

Add a keyword argument `coord_system` which can take the values `"spacecraft"` or `"ORviewer"`.

**Comment by jeanconn** [comment]
I had this on my plate but just realized my understanding is not lining up with "have zero be defined as the ECI z-axis" as I thought yaw=0 would define the placement of X.
